<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Python on Star5o的博客</title>
    <link>https://yakaili.github.io/zh-cn/tags/python/</link>
    <description>Recent content in Python on Star5o的博客</description>
    <generator>Hugo -- gohugo.io</generator>
    <copyright>Star5o Love Haohao</copyright>
    <lastBuildDate>Sun, 27 Nov 2022 00:00:00 +0000</lastBuildDate><atom:link href="https://yakaili.github.io/zh-cn/tags/python/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>linux-Python3-UnicodeEncodeError: &#39;ascii&#39; codec can&#39;t encode characters in position 0-1: ordinal not in range(128)</title>
      <link>https://yakaili.github.io/zh-cn/post/2022/11/27/python3-unicodeencodeerror/</link>
      <pubDate>Sun, 27 Nov 2022 00:00:00 +0000</pubDate>
      
      <guid>https://yakaili.github.io/zh-cn/post/2022/11/27/python3-unicodeencodeerror/</guid>
      <description>错误说明 今天在服务器上使用python3执行python文件时报错。 报错所在行语句： 1 print(&amp;#34;读取图片文件耗费时间：%d秒&amp;#34; % time_elapsed) 报错信息： 1 UnicodeEncodeError: &amp;#39;ascii&amp;#39; codec can&amp;#39;t encode characters in position 0-1: ordinal not in range(128) 问题分析 1、</description>
    </item>
    
  </channel>
</rss>
