<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Troubleshooting on Star5o的博客</title>
    <link>https://www.gnn.ac.cn/zh-cn/tags/troubleshooting/</link>
    <description>Recent content in Troubleshooting on Star5o的博客</description>
    <generator>Hugo -- gohugo.io</generator>
    <copyright>Star5o Love Haohao</copyright>
    <lastBuildDate>Thu, 15 Dec 2022 00:00:00 +0000</lastBuildDate><atom:link href="https://www.gnn.ac.cn/zh-cn/tags/troubleshooting/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>commit了一个大文件导致本地仓库无法推送到github的问题解决方法</title>
      <link>https://www.gnn.ac.cn/zh-cn/post/2022/12/15/git-commit-large-file-error/</link>
      <pubDate>Thu, 15 Dec 2022 00:00:00 +0000</pubDate>
      
      <guid>https://www.gnn.ac.cn/zh-cn/post/2022/12/15/git-commit-large-file-error/</guid>
      <description>报错 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 枚举对象中: 57, 完成. 对象计数中: 100% (57/57), 完成. 使用 8 个线程进行压缩 压缩对象中: 100% (37/37), 完成. 写入对象中: 28% (11/38) 写入对象中: 100% (38/38), 365.92 MiB | 4.85 MiB/s, 完成. 总共 38（差异 23），复用 0（差异</description>
    </item>
    
    <item>
      <title>linux-Python3-UnicodeEncodeError: &#39;ascii&#39; codec can&#39;t encode characters in position 0-1: ordinal not in range(128)</title>
      <link>https://www.gnn.ac.cn/zh-cn/post/2022/11/27/python3-unicodeencodeerror/</link>
      <pubDate>Sun, 27 Nov 2022 00:00:00 +0000</pubDate>
      
      <guid>https://www.gnn.ac.cn/zh-cn/post/2022/11/27/python3-unicodeencodeerror/</guid>
      <description>错误说明 今天在服务器上使用python3执行python文件时报错。 报错所在行语句： 1 print(&amp;#34;读取图片文件耗费时间：%d秒&amp;#34; % time_elapsed) 报错信息： 1 UnicodeEncodeError: &amp;#39;ascii&amp;#39; codec can&amp;#39;t encode characters in position 0-1: ordinal not in range(128) 问题分析 1、</description>
    </item>
    
  </channel>
</rss>
